# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
  application:
    name: sbcamel
server:
  context-path: /${spring.application.name}
  port: 8080

logging:
  file: ${spring.application.name}.log
  level:
    org.apache.camel: debug
    org.springframework.web: debug
    root: debug