# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
  application:
    name: spring-boot-camel
  profiles:
    active: @activatedProperties@
server:
  context-path: /${spring.application.name}
  port: 8080
logging:
  file: ${catalina.home}/logs/${spring.application.name}.log
  level:
    org.apache.camel: warn
    org.springframework.web: warn
    root: warn