# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
  application:
    name: sbcamel
  profiles:
    active: @activatedProperties@
server:
  context-path: /${spring.application.name}
  port: 8080
logging:
  file: ${catalina.home}/logs/${spring.application.name}.log
  level:
    org.apache.camel: warn
    org.springframework.web: warn
    root: warn

# ===================================================================
# Camel specific properties
# ===================================================================
camel:
  component:
    servlet:
      mapping:
        context-path: /api/*
      servlet-name: CamelServlet
    rest:
      component-name: servlet
  rest:
    binding-mode: json
    json-data-format: json-gson
    component: servlet
    api-context-path: /api-doc
    enable-cors: true
    api-property:
      api.title: Camel App Example
      api.version: 1.0.0